name: CullingGames
version: '1.0-SNAPSHOT'
main: cronozx.cullinggames.CullingGames
api-version: '1.20'
authors: [ cronozx ]
softdepend:
  - HuskHomes

commands:
  queue:
    description: Joins queue
    usage: /queue
  reload:
    description: Reloads config
    usage: /reload
  starttest:
      description: test start
      usage: /starttest
